#!/bin/sh

uci -q batch <<-EOF >/dev/null
  delete network.vpn
  set network.vpn=interface
  set network.vpn.proto=none
  set network.vpn.ifname=ppp+
  set network.vpn.auto=1
  commit network
EOF

uci -q batch <<-EOF >/dev/null
  delete firewall.vpn
  set firewall.vpn="zone"
  set firewall.vpn.name="vpn"
  add_list firewall.vpn.network="vpn"
  set firewall.vpn.family="ipv4"
  set firewall.vpn.input="ACCEPT"
  set firewall.vpn.forward="REJECT"
  set firewall.vpn.output="ACCEPT"
  delete firewall.vpn2lan
  add firewall forwarding
  rename firewall.@forwarding[-1]="vpn2lan"
  set firewall.@forwarding[-1].src="vpn"
  set firewall.@forwarding[-1].dest="lan"
  delete firewall.vpn2wan
  add firewall forwarding
  rename firewall.@forwarding[-1]="vpn2wan"
  set firewall.@forwarding[-1].src="vpn"
  set firewall.@forwarding[-1].dest="wan"
  delete firewall.lan2vpn
  add firewall forwarding
  rename firewall.@forwarding[-1]="lan2vpn"
  set firewall.@forwarding[-1].src="lan"
  set firewall.@forwarding[-1].dest="vpn"
  delete firewall.pptp
  add firewall rule 
  rename firewall.@rule[-1]="pptp"
  set firewall.@rule[-1].name="pptp"
  set firewall.@rule[-1].target="ACCEPT"
  set firewall.@rule[-1].src="wan"
  set firewall.@rule[-1].proto="tcp"
  set firewall.@rule[-1].dest_port="1723"
  delete firewall.gre
  add firewall rule 
  rename firewall.@rule[-1]="gre"
  set firewall.@rule[-1].name="gre"
  set firewall.@rule[-1].target="ACCEPT"
  set firewall.@rule[-1].src="wan"
  set firewall.@rule[-1].proto="47"
  commit firewall
EOF

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@pptpd[-1]
	add ucitrack pptpd
	set ucitrack.@pptpd[-1].init=pptpd
	commit ucitrack
EOF

/etc/init.d/pptpd enable && /etc/init.d/pptpd restart

rm -f /tmp/luci-indexcache
exit 0
