#!/bin/sh

uci -q batch <<-EOF > /dev/null
	delete ucitrack.@udpspeeder[-1]
	add ucitrack udpspeeder
	set ucitrack.@udpspeeder[-1].init=udpspeeder
	commit ucitrack
EOF

general=$(uci -q get udpspeeder.@general[-1])
if [ -z "$general" ]; then
	uci -q add udpspeeder general
fi
if [ "$general"x != "general"x ]; then
	uci -q batch <<-EOF > /dev/null
		rename udpspeeder.@general[-1]="general"
		set udpspeeder.@general[-1].server="nil"
		commit udpspeeder
	EOF
fi

rm -rf /tmp/luci-indexcache /tmp/luci-modulecache
exit 0
