#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@dnscrypt-proxy2[-1]
	add ucitrack dnscrypt-proxy2
	set ucitrack.@dnscrypt-proxy2[-1].init=dnscrypt-proxy2
	commit ucitrack
EOF

[ -f /etc/init.d/dnscrypt-proxy ] && /etc/init.d/dnscrypt-proxy disable && /etc/init.d/dnscrypt-proxy stop

rm -f /tmp/luci-indexcache
exit 0
