#!/bin/sh /etc/rc.common

START=99
STOP=10

lan_addr="$(uci get network.lan.ipaddr)"

[ "$(uci get unblockmusic.@unblockmusic[0].enable_hijack)" = "1" ] && hijack_ways="$(uci get unblockmusic.@unblockmusic[0].hijack_ways)"
[ "$(uci get unblockmusic.@unblockmusic[0].pub_access 2>/dev/null)" = "1" ] && addr="0.0.0.0" || addr="${lan_addr}"
[ "$(uci get unblockmusic.@unblockmusic[0].strict_mode 2>/dev/null)" = "1" ] && strict_mode="-s"
[ "$(uci get unblockmusic.@unblockmusic[0].set_netease_server_ip 2>/dev/null)"  = "1" ] && netease_server_ip="-f $(uci get unblockmusic.@unblockmusic[0].netease_server_ip)"
[ "$(uci get unblockmusic.@unblockmusic[0].enable_proxy 2>/dev/null)" = "1" ] && proxy_server_ip="-u $(uci get unblockmusic.@unblockmusic[0].proxy_server_ip)"

enable="$(uci get unblockmusic.@unblockmusic[0].enabled)"
type="$(uci get unblockmusic.@unblockmusic[0].musicapptype)"
http_port="$(uci get unblockmusic.@unblockmusic[0].http_port)"
https_port="$(uci get unblockmusic.@unblockmusic[0].https_port)"

set_ipset(){
	if [ "${set_type}" = "start" ]; then
		mkdir -p /tmp/dnsmasq.d
		echo "ipset=/music.163.com/music" > /tmp/dnsmasq.d/unblockmusic
		echo "ipset=/interface.music.163.com/music" >> /tmp/dnsmasq.d/unblockmusic
		echo "address=/music.httpdns.c.163.com/" >> /tmp/dnsmasq.d/unblockmusic
		/etc/init.d/dnsmasq restart >/dev/null 2>&1

		mkdir -p /var/etc
		[ "$(uci get unblockmusic.@unblockmusic[0].ipset_forward_nohttps 2>/dev/null)" = "1" ] || forward_https="iptables -t nat -A cloud_music -p tcp --dport 443 -j REDIRECT --to-ports ${https_port}"
		cat > "/var/etc/unblockmusic.include" <<-EOF
ip route del 223.252.199.10 2>/dev/null
iptables -t nat -D prerouting_rule -p tcp -m set --match-set music dst -j cloud_music 2>/dev/null
iptables -t nat -F cloud_music 2>/dev/null
iptables -t nat -X cloud_music 2>/dev/null
if ! ipset list music >/dev/null; then
	ipset create music hash:ip
	wget http://httpdns.n.netease.com/httpdns/v2/d?domain=music.163.com,interface.music.163.com,interface3.music.163.com,apm.music.163.com,apm3.music.163.com,clientlog.music.163.com,clientlog3.music.163.com -O- | grep -Eo '[0-9]+?\.[0-9]+?\.[0-9]+?\.[0-9]+?' | sort | uniq | awk '{print "ipset -! add music "$1}' | sh
fi
iptables -t nat -N cloud_music
iptables -t nat -A cloud_music -p tcp --dport 80 -j REDIRECT --to-ports ${http_port}
${forward_https}
iptables -t nat -A prerouting_rule -p tcp -m set --match-set music dst -j cloud_music
ip route add 223.252.199.10 dev lo
		EOF
		sh /var/etc/unblockmusic.include
	elif [ "${set_type}" = "stop" ]; then
		echo "" > /var/etc/unblockmusic.include
		ip route del 223.252.199.10 2>/dev/null
		iptables -t nat -D prerouting_rule -p tcp -m set --match-set music dst -j cloud_music 2>/dev/null
		iptables -t nat -F cloud_music 2>/dev/null
		iptables -t nat -X cloud_music 2>/dev/null

		rm -f /tmp/dnsmasq.d/unblockmusic
		/etc/init.d/dnsmasq restart >/dev/null 2>&1
	fi
}

set_hosts(){
	if [ "${set_type}" = "start" ]; then
		cfg_name="$(uci add dhcp domain)"
		uci set dhcp."${cfg_name}".name='music.163.com'
		uci set dhcp."${cfg_name}".ip="${lan_addr}"
		uci commit dhcp

		cfg_name="$(uci add dhcp domain)"
		uci set dhcp."${cfg_name}".name='interface.music.163.com'
		uci set dhcp."${cfg_name}".ip="${lan_addr}"
		uci commit dhcp

		cfg_name="$(uci add dhcp domain)"
		uci set dhcp."${cfg_name}".name='music.httpdns.c.163.com'
		uci set dhcp."${cfg_name}".ip="127.0.0.1"
		uci commit dhcp

		ip route add 223.252.199.10 dev lo
	elif [ "${set_type}" = "stop" ]; then
		music_id1="$(uci show dhcp| grep "music.163.com"| grep -Eo "domain\[[0-9]+\]"| grep -Eo "[0-9]+")"
		[ -n "${music_id1}" ] && uci delete dhcp.@domain["${music_id1}"]

		music_id2="$(uci show dhcp| grep "interface.music.163.com"| grep -Eo "domain\[[0-9]+\]"| grep -Eo "[0-9]+")"
		[ -n "${music_id2}" ] && uci delete dhcp.@domain["${music_id2}"]

		music_id3="$(uci show dhcp| grep "music.httpdns.c.163.com"| grep -Eo "domain\[[0-9]+\]"| grep -Eo "[0-9]+")"
		[ -n "${music_id3}" ] && uci delete dhcp.@domain["${music_id3}"]

		[ -n "$(uci changes 2>/dev/null)" ] && uci commit dhcp
		ip route del 223.252.199.10 2>/dev/null
	fi
}

start()
{
	[ "${enable}" = "0" ] && exit 0

	ping -c1 114.114.114.114 >/dev/null 2>&1
	[ "$?" != "0" ] && sleep 15

	if [ "${type}" = "default" ]; then
		node /usr/share/unblockmusic/app.js -a ${addr} -p ${http_port}:${https_port} ${netease_server_ip} ${proxy_server_ip} ${strict_mode} >/tmp/unblockmusic.log 2>&1 &
	elif [ "${type}" = "all" ]; then
		node /usr/share/unblockmusic/app.js -a ${addr} -p ${http_port}:${https_port} -o kuwo migu xiami kugou qq joox netease ${netease_server_ip} ${proxy_server_ip} ${strict_mode} >/tmp/unblockmusic.log 2>&1 &
	else
		node /usr/share/unblockmusic/app.js -a ${addr} -p ${http_port}:${https_port} -o ${type} ${netease_server_ip} ${proxy_server_ip} ${strict_mode} >/tmp/unblockmusic.log 2>&1 &
	fi

	set_type="start"
	if [ "${hijack_ways}" = "use_ipset" ]; then
		set_ipset
	elif [ "${hijack_ways}" = "use_hosts" ]; then
		set_hosts
	fi

	/usr/share/logcheck.sh >/dev/null 2>&1 &
}

stop()
{
	kill -9 "$(ps | grep app.js | grep -v grep | awk '{print $1}')" >/dev/null 2>&1
	kill -9 "$(ps | grep logcheck.sh | grep -v grep | awk '{print $1}')" >/dev/null 2>&1

	rm -f /tmp/unblockmusic.log

	set_type="stop"
	set_ipset
	set_hosts
}
