#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@dnscrypt-proxy_2[-1]
	add ucitrack dnscrypt-proxy_2
	set ucitrack.@dnscrypt-proxy_2[-1].init=dnscrypt-proxy_2
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
